package helpers

// random string generation related function

import (
	"math/rand"
	"time"
)

// func randomString() generates a random string of the requested length
// the random string will be based on the hardcoded character set (aplhanumeric characters)
// the seed used is the Unix Nano seconds, so the chance of returning a same randon string is very rare.
// Note: the random string generated by this function is prefixed to the original file, so even if the random string generated is same for two files, the risk of overlap still reduces because of prefixing it with original file name
func randomString(strlen int) string {
	rand.Seed(time.Now().UTC().UnixNano())
	const chars = "abcdefghijklmnopqrstuvwxyz0123456789"
	result := make([]byte, strlen)
	for i := 0; i < strlen; i++ {
		result[i] = chars[rand.Intn(len(chars))]
	}
	return string(result)
	//source: http://siongui.github.io/2015/04/13/go-generate-random-string/
}
